message("${BoldGreen}---- Selected options begin ----${ColourReset}")

option(ENABLE_GCOV "set ifm_nettle gcov option" OFF)
if (ENABLE_GCOV STREQUAL "ON")
    message("${Green}--  Enable gcov${ColourReset}")
endif()

option(ENABLE_LIBIFM_NETTLE "enable ifm_nettle libifm_nettle option" ON)
if (ENABLE_LIBIFM_NETTLE STREQUAL "ON")
    add_definitions(-DENABLE_LIBIFM_NETTLE=1)
    set(ENABLE_LIBIFM_NETTLE 1)
    message("${Green}--  Enable libifm_nettle${ColourReset}")
endif()

option(ENABLE_LIBIFM_LIBGCRYPT "enable ifm_libgcrypt libifm_libgcrypt option" ON)
if (ENABLE_LIBIFM_LIBGCRYPT STREQUAL "ON")
    add_definitions(-DENABLE_LIBIFM_LIBGCRYPT=1)
    set(ENABLE_LIBIFM_LIBGCRYPT 1)
    message("${Green}--  Enable libifm_libgcrypt${ColourReset}")
endif()

option(ENABLE_LIBIFM_LIBXCRYPT "enable ifm_libxcrypt libifm_libxcrypt option" ON)
if (ENABLE_LIBIFM_LIBXCRYPT STREQUAL "ON")
    add_definitions(-DENABLE_LIBIFM_LIBXCRYPT=1)
    set(ENABLE_LIBIFM_LIBXCRYPT 1)
    message("${Green}--  Enable libifm_libxcrypt${ColourReset}")
endif()

option(ENABLE_LIBIFM_LIBHV2EV "enable ifm_libhv2ev libifm_libhv2ev option" ON)
if (ENABLE_LIBIFM_LIBHV2EV STREQUAL "ON")
    add_definitions(-DENABLE_LIBIFM_LIBHV2EV=1)
    set(ENABLE_LIBIFM_LIBHV2EV 1)
    message("${Green}--  Enable libifm_libhv2ev${ColourReset}")
endif()

option(ENABLE_LIBIFM_LIBVERTO "enable ifm_libverto libifm_libverto option" ON)
if (ENABLE_LIBIFM_LIBVERTO STREQUAL "ON")
    add_definitions(-DENABLE_LIBIFM_LIBVERTO=1)
    set(ENABLE_LIBIFM_LIBVERTO 1)
    message("${Green}--  Enable libifm_libverto${ColourReset}")
endif()

message("${BoldGreen}---- Selected options end ----${ColourReset}")
